### ISSUE TITLE
因common.js与about.js中的两处错误,无法在非本机上部署该程序

### ISSUE THREAD

**Issue by qqice233** [6mb/Microsoft-365-Admin#1]
在内网另一台机器部署您的程序时,遇到了如下问题:
配置完成,打开网页后,直接弹出错误窗口:"服务器错误，请稍后再试~"
f12检查发现异常
![Snipaste_2020-08-17_01-20-59](https://user-images.githubusercontent.com/39629131/90340049-f52dfe80-e027-11ea-9f16-a6409c9809cd.png)
经检查,猜测是因为common.js与about.js中,将path定义成了127.0.0.1:8099,导致将本程序部署到非本机上时,无法正确访问api所致.
希望大佬修改,谢谢!

**Comment by 6mb** [comment]
前端不太会哦，要不你把前端文件单独读部署，修改 config.js 中的请求地址，或者能告诉我下怎么修改哦

**Comment by 6mb** [comment]
已解决，请更新版本
