### ISSUE TITLE
请教大佬提权需要什么API呢

### ISSUE THREAD

**Issue by Car-shock** [6mb/Microsoft-365-Admin#28]
已经按照要求添加了：
应用程序的API：User.ReadWrite.All、Directory.ReadWrite.All
委派的API：User.ReadWrite.All、Directory.ReadWrite.All、Directory.AccessAsUser.All
但是依然不能提权，其他功能正常。

**Comment by 6mb** [comment]
RoleManagement.ReadWrite.Directory 权限
